from app.bot.telegram.texts.admin.calendar import (
    ADMIN_CALENDAR_CANCELLED,
    ADMIN_CALENDAR_EDIT_MENU,
    ADMIN_CALENDAR_ENTER_SEASON_NEW_NAME,
    ADMIN_CALENDAR_ENTER_SEASON_NEW_START,
    ADMIN_CALENDAR_INVALID_DATE,
    ADMIN_CALENDAR_SCORING_CONFIG_NOT_FOUND,
    ADMIN_CALENDAR_SEASON_ALREADY_HANDLED,
    ADMIN_CALENDAR_SEASON_CONFLICT,
    ADMIN_CALENDAR_SEASON_CREATED,
    ADMIN_CALENDAR_SEASON_NAME_EXISTS,
    ADMIN_CALENDAR_SEASON_START_INVALID,
)

__all__ = [
    "ADMIN_CALENDAR_CANCELLED",
    "ADMIN_CALENDAR_EDIT_MENU",
    "ADMIN_CALENDAR_ENTER_SEASON_NEW_NAME",
    "ADMIN_CALENDAR_ENTER_SEASON_NEW_START",
    "ADMIN_CALENDAR_INVALID_DATE",
    "ADMIN_CALENDAR_SCORING_CONFIG_NOT_FOUND",
    "ADMIN_CALENDAR_SEASON_ALREADY_HANDLED",
    "ADMIN_CALENDAR_SEASON_CONFLICT",
    "ADMIN_CALENDAR_SEASON_CREATED",
    "ADMIN_CALENDAR_SEASON_NAME_EXISTS",
    "ADMIN_CALENDAR_SEASON_START_INVALID",
]
