TOURNAMENT_HUB_TITLE = "🏆 Турниры"
OPEN_TOURNAMENTS_TITLE = "🔑 Открытые турниры"
OPEN_TOURNAMENTS_EMPTY = "Открытых турниров нет."
OPEN_TOURNAMENT_EDITING_INFO = "Результаты, фото и комбинации редактируются в меню администратора."
OPEN_TOURNAMENT_PLAYERS_EMPTY = "В турнире пока нет игроков."
OPEN_TOURNAMENT_DELETE_WARNING = "Будут удалены данные игрока только из этого турнира."
OPEN_TOURNAMENT_PLAYER_DELETED = "Игрок удалён из турнира."
OPEN_TOURNAMENT_PLAYER_STALE = "Игрок уже не найден в этом турнире."
OPEN_TOURNAMENT_DELETE_REWARD_CONFLICT = "Нельзя удалить игрока: для этого турнира уже есть бонус."
TOURNAMENT_PLANNING_UNAVAILABLE = "Расписание недоступно."
CALENDAR_EMPTY_WEEK_HINT = (
    "Для правильного чередования воскресных турниров рекомендуется заполнять недели по порядку."
)
CALENDAR_TOURNAMENT_CREATED = "Турнир создан. Регистрация пока закрыта."
CALENDAR_WEEK_CREATED = "Неделя создана. Регистрация пока закрыта."
CALENDAR_WEEK_APPROVED = "Неделя утверждена."
CALENDAR_TYPE_CHANGED = "Тип турнира изменён."
CALENDAR_TOURNAMENT_DELETED = "Турнир удалён."
CALENDAR_UNAVAILABLE = "Календарь недоступен."
CALENDAR_DATE_BUSY = "На эту дату уже есть турнир."
CALENDAR_TOURNAMENT_NOT_EDITABLE = "Этот турнир нельзя изменить из календаря."
CALENDAR_NO_APPROVAL_TARGETS = "В этой неделе нечего утверждать."
CALENDAR_WEEK_NOT_EMPTY = "В этой неделе уже есть турниры."
CALENDAR_TOURNAMENT_CANCELLED_USER = "Турнир {tournament} отменён."
