"""create initial tables

Revision ID: a4e9ba37fa36
Revises:
Create Date: 2026-06-28 23:13:46.915346
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a4e9ba37fa36"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "active", "blocked", name="player_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("user", "admin", "superadmin", name="player_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_admin_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "full_name IS NOT NULL OR nickname IS NOT NULL",
            name=op.f("ck_players_identity_present"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_admin_id"],
            ["players.id"],
            name=op.f("fk_players_approved_by_admin_id_players"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("full_name", name=op.f("uq_players_full_name")),
        sa.UniqueConstraint("nickname", name=op.f("uq_players_nickname")),
    )
    op.create_index(op.f("ix_players_status"), "players", ["status"], unique=False)
    op.create_index(op.f("ix_players_telegram_id"), "players", ["telegram_id"], unique=True)
    op.create_table(
        "scoring_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("place_1_coefficient", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("place_2_coefficient", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("place_3_coefficient", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("place_4_coefficient", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("place_5_coefficient", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("knockout_points", sa.Integer(), nullable=False),
        sa.Column("boss_knockout_points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "place_1_coefficient + place_2_coefficient + place_3_coefficient "
            "+ place_4_coefficient + place_5_coefficient = 1",
            name=op.f("ck_scoring_configs_place_coefficients_sum"),
        ),
        sa.CheckConstraint(
            "boss_knockout_points >= 0",
            name=op.f("ck_scoring_configs_boss_knockout_points_nonnegative"),
        ),
        sa.CheckConstraint(
            "knockout_points >= 0", name=op.f("ck_scoring_configs_knockout_points_nonnegative")
        ),
        sa.CheckConstraint(
            "place_1_coefficient >= 0 AND place_1_coefficient <= 1",
            name=op.f("ck_scoring_configs_place_1_coefficient_range"),
        ),
        sa.CheckConstraint(
            "place_2_coefficient >= 0 AND place_2_coefficient <= 1",
            name=op.f("ck_scoring_configs_place_2_coefficient_range"),
        ),
        sa.CheckConstraint(
            "place_3_coefficient >= 0 AND place_3_coefficient <= 1",
            name=op.f("ck_scoring_configs_place_3_coefficient_range"),
        ),
        sa.CheckConstraint(
            "place_4_coefficient >= 0 AND place_4_coefficient <= 1",
            name=op.f("ck_scoring_configs_place_4_coefficient_range"),
        ),
        sa.CheckConstraint(
            "place_5_coefficient >= 0 AND place_5_coefficient <= 1",
            name=op.f("ck_scoring_configs_place_5_coefficient_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_configs")),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scoring_config_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=False),
        sa.Column("ends_at", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "closed", name="season_status", native_enum=False),
            nullable=False,
        ),
        sa.CheckConstraint("starts_at <= ends_at", name=op.f("ck_seasons_date_range")),
        sa.ForeignKeyConstraint(
            ["scoring_config_id"],
            ["scoring_configs.id"],
            name=op.f("fk_seasons_scoring_config_id_scoring_configs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("name", name=op.f("uq_seasons_name")),
    )
    op.create_index(op.f("ix_seasons_status"), "seasons", ["status"], unique=False)
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("points_pool", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "closed", "cancelled", name="tournament_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status != 'closed' OR points_pool IS NOT NULL",
            name=op.f("ck_tournaments_closed_has_points_pool"),
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_tournaments_capacity_positive")),
        sa.CheckConstraint(
            "points_pool IS NULL OR points_pool >= 0",
            name=op.f("ck_tournaments_points_pool_nonnegative"),
        ),
        sa.CheckConstraint("type IN (1, 2, 3)", name=op.f("ck_tournaments_type_supported")),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_tournaments_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournaments")),
    )
    op.create_index(op.f("ix_tournaments_date"), "tournaments", ["date"], unique=False)
    op.create_index(op.f("ix_tournaments_season_id"), "tournaments", ["season_id"], unique=False)
    op.create_index(op.f("ix_tournaments_status"), "tournaments", ["status"], unique=False)
    op.create_table(
        "tournament_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("registered", "cancelled", name="registration_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'registered' AND cancelled_at IS NULL) "
            "OR (status = 'cancelled' AND cancelled_at IS NOT NULL)",
            name=op.f("ck_tournament_registrations_cancellation_state"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_tournament_registrations_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_registrations_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_registrations")),
        sa.UniqueConstraint(
            "tournament_id",
            "player_id",
            name="uq_tournament_registrations_tournament_player",
        ),
    )
    op.create_index(
        op.f("ix_tournament_registrations_player_id"),
        "tournament_registrations",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_status"),
        "tournament_registrations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_tournament_id"),
        "tournament_registrations",
        ["tournament_id"],
        unique=False,
    )
    op.create_table(
        "tournament_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("place", sa.Integer(), nullable=False),
        sa.Column("knockouts_count", sa.Integer(), nullable=False),
        sa.Column("boss_knockouts_count", sa.Integer(), nullable=False),
        sa.Column("tournament_points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("knockout_points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("bonus_points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "boss_knockouts_count >= 0",
            name=op.f("ck_tournament_results_boss_knockouts_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "knockout_points >= 0", name=op.f("ck_tournament_results_knockout_points_nonnegative")
        ),
        sa.CheckConstraint(
            "knockouts_count >= 0", name=op.f("ck_tournament_results_knockouts_count_nonnegative")
        ),
        sa.CheckConstraint("place > 0", name=op.f("ck_tournament_results_place_positive")),
        sa.CheckConstraint(
            "tournament_points >= 0",
            name=op.f("ck_tournament_results_tournament_points_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_tournament_results_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_results_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_results")),
        sa.UniqueConstraint(
            "tournament_id",
            "place",
            name="uq_tournament_results_tournament_place",
        ),
        sa.UniqueConstraint(
            "tournament_id",
            "player_id",
            name="uq_tournament_results_tournament_player",
        ),
    )
    op.create_index(
        op.f("ix_tournament_results_player_id"), "tournament_results", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_results_tournament_id"),
        "tournament_results",
        ["tournament_id"],
        unique=False,
    )
    op.execute(
        sa.text(
            """
            INSERT INTO scoring_configs (
                place_1_coefficient,
                place_2_coefficient,
                place_3_coefficient,
                place_4_coefficient,
                place_5_coefficient,
                knockout_points,
                boss_knockout_points,
                created_at,
                updated_at
            )
            VALUES (
                0.45,
                0.25,
                0.15,
                0.10,
                0.05,
                15,
                60,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tournament_results_tournament_id"), table_name="tournament_results")
    op.drop_index(op.f("ix_tournament_results_player_id"), table_name="tournament_results")
    op.drop_table("tournament_results")
    op.drop_index(
        op.f("ix_tournament_registrations_tournament_id"), table_name="tournament_registrations"
    )
    op.drop_index(op.f("ix_tournament_registrations_status"), table_name="tournament_registrations")
    op.drop_index(
        op.f("ix_tournament_registrations_player_id"), table_name="tournament_registrations"
    )
    op.drop_table("tournament_registrations")
    op.drop_index(op.f("ix_tournaments_status"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_season_id"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_date"), table_name="tournaments")
    op.drop_table("tournaments")
    op.drop_index(op.f("ix_seasons_status"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_table("scoring_configs")
    op.drop_index(op.f("ix_players_telegram_id"), table_name="players")
    op.drop_index(op.f("ix_players_status"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
