MAIN_SCHEDULE = "🗓 Расписание"
MAIN_ADDRESS = "📍 Как нас найти"
MAIN_REGISTER = "✅ Записаться"
MAIN_CANCEL_REGISTRATION = "🚫 Отменить запись"
MAIN_RATING = "🏆 Рейтинг"
MAIN_PROFILE = "👤 Твой профиль"
MAIN_ADMIN = "🛠 Админ-панель"

CONFIRM = "✅ Подтвердить"
RESTART = "🔄 Ввести заново"
CANCEL = "❌ Отмена"
EDIT = "✏️ Исправить"

ADMIN_APPROVE = "✅ Одобрить"
ADMIN_APPROVE_WITH_HISTORY = "🔗 Связать с историей"
ADMIN_APPROVE_AS_NEW = "🆕 Сохранить нового пользователя"
ADMIN_REJECT = "🚫 Отклонить"
ADMIN_CANCEL = "❌ Отмена"
ADMIN_PANEL_REGISTRATIONS = "📝 Заявки на регистрацию"
ADMIN_PANEL_ADD_ADMIN = "➕ Добавить админа"
ADMIN_PANEL_CALENDAR = "🗓 Календарь"
ADMIN_PANEL_RESULTS = "🏁 Внести результат"
ADMIN_PANEL_REGISTER_PLAYER = "📝 Зарегать игрока на турнир"
ADMIN_PANEL_SUPERADMIN = "👑 Суперадмин"
ADMIN_PANEL_BACK = "⬅️ Назад"
ADMIN_PANEL_EXIT = "⬅️ Выход"
ADMIN_ADD_CONFIRM = "✅ Назначить админом"
ADMIN_RESULTS_POOL = "💰 Пул"
ADMIN_RESULTS_PLAYERS = "👥 Игроки"
ADMIN_RESULTS_CLOSE = "✅ Закрыть турнир"
ADMIN_RESULTS_SAVE = "✅ Сохранить"
ADMIN_TOURNAMENT_REGISTRATION_SEARCH = "🔎 Найти игрока"
ADMIN_TOURNAMENT_REGISTRATION_SEARCH_AGAIN = "🔎 Искать заново"
ADMIN_CALENDAR_SEASONS = "⏳ Сезоны"
ADMIN_CALENDAR_TOURNAMENTS = "🏆 Турниры"
ADMIN_CALENDAR_OPEN = "✅ Создать"
ADMIN_CALENDAR_EDIT = "✏️ Изменить"
ADMIN_CALENDAR_CANCEL = "❌ Отмена"
ADMIN_CALENDAR_BACK = "⬅️ Назад"
ADMIN_SEASON_EDIT_NAME = "✏️ Название"
ADMIN_SEASON_EDIT_START = "📅 Дата начала"

RATING_CURRENT_SEASON = "🏆 Текущий сезон"
RATING_ALL_TIME = "🏆⏳ За все время"
RATING_KNOCKOUTS_CURRENT_SEASON = "🥊 Нокауты"
RATING_KNOCKOUTS_ALL_TIME = "🥊⏳ Нокауты за все время"
RATING_CLOSE = "❌ Закрыть рейтинг"

PROFILE_CURRENT_SEASON = "🏆 За текущий сезон"
PROFILE_ALL_TIME = "⏳ За все время"

SELECTED_PREFIX = "✔️ "
