MAIN_SCHEDULE = "🗓 Расписание"
MAIN_ADDRESS = "📍 Как нас найти"
MAIN_REGISTER = "✅ Записаться"
MAIN_CANCEL_REGISTRATION = "🚫 Отменить запись"
MAIN_RATING = "🏆 Рейтинг"
MAIN_PROFILE = "👤 Твой профиль"
MAIN_ADMIN = "🛠 Админ-панель"

REGISTRATION_FULL_NAME = "🪪 Фамилия и имя"
REGISTRATION_NICKNAME = "🎮 Никнейм"
REGISTRATION_BOTH = "🪪🎮 Фамилия и имя + никнейм"
CONFIRM = "✅ Подтвердить"
RESTART = "🔄 Ввести заново"
CANCEL = "❌ Отмена"
EDIT = "✏️ Исправить"

ADMIN_APPROVE = "✅ Одобрить"
ADMIN_APPROVE_WITH_HISTORY = "🔗 Связать с историей"
ADMIN_APPROVE_AS_NEW = "🆕 Сохранить нового пользователя"
ADMIN_REJECT = "🚫 Отклонить"
ADMIN_CANCEL = "❌ Отмена"
ADMIN_PANEL_REGISTRATIONS = "📝 Заявки на регистрацию"
ADMIN_PANEL_ADD_ADMIN = "➕ Добавить админа"
ADMIN_PANEL_CALENDAR = "🗓 Календарь"
ADMIN_PANEL_RESULTS = "🏁 Внести результат"
ADMIN_PANEL_REGISTER_PLAYER_TODO = "📝 Зарегать игрока на турнир — НЕТ ОБР!"
ADMIN_PANEL_EXIT = "⬅️ Выход"
ADMIN_ADD_CONFIRM = "✅ Назначить админом"
ADMIN_RESULTS_POOL = "💰 Пул"
ADMIN_RESULTS_PLAYERS = "👥 Игроки"
ADMIN_RESULTS_CHECK = "🔎 Проверить"
ADMIN_RESULTS_CLOSE = "✅ Закрыть турнир"
ADMIN_RESULTS_SAVE = "✅ Сохранить"
ADMIN_CALENDAR_SEASONS = "⏳ Сезоны"
ADMIN_CALENDAR_TOURNAMENTS = "🏆 Турниры"
ADMIN_CALENDAR_OPEN = "✅ Создать"
ADMIN_CALENDAR_EDIT = "✏️ Изменить"
ADMIN_CALENDAR_CANCEL = "❌ Отмена"
ADMIN_SEASON_EDIT_NAME = "✏️ Название"
ADMIN_SEASON_EDIT_START = "📅 Дата начала"
ADMIN_SEASON_EDIT_END = "🏁 Дата окончания"
ADMIN_TOURNAMENT_EDIT_TYPE = "🏷 Тип"
ADMIN_TOURNAMENT_EDIT_ECONOMY = "💰 Вход / аддон"
ADMIN_TOURNAMENT_EDIT_REBUYS = "🔁 Ребаи"

RATING_CURRENT_SEASON = "🏆 Текущий сезон"
RATING_ALL_TIME = "🏆⏳ За все время"
RATING_KNOCKOUTS_CURRENT_SEASON = "💥 Нокауты"
RATING_KNOCKOUTS_ALL_TIME = "💥⏳ Нокауты за все время"
RATING_CLOSE = "❌ Закрыть рейтинг"

PROFILE_CURRENT_SEASON = "🏆 За текущий сезон"
PROFILE_ALL_TIME = "⏳ За все время"

SELECTED_PREFIX = "✔️ "
