ADMIN_CALENDAR_PROMPT = "Меню для создания сезонов и турниров в базе данных."
ADMIN_CALENDAR_CANCELLED = "Отмена."
ADMIN_CALENDAR_EMPTY_SEASONS = "Нет конфигураций начисления рейтинга."
ADMIN_CALENDAR_EMPTY_TOURNAMENTS = "Не удалось создать расписание."
ADMIN_CALENDAR_TOURNAMENT_DATE_EXISTS = "На эту дату турнир уже создан."
ADMIN_CALENDAR_TOURNAMENT_WEEK_EMPTY = "Суперадмин. На будущую неделю нужно создать турниры!"
ADMIN_CALENDAR_TOURNAMENT_WEEK_PARTIAL = "⚠️ Расписание заполнено не полностью."
ADMIN_CALENDAR_SEASON_CREATED = "Сезон создан."
SEASON_CREATED_TITLE = "Создан новый сезон:"
SEASON_PROPOSAL_PREVIEW_TITLE = "🏆 Новый сезон"
SEASON_NAME_LABEL = "Название"
SEASON_CURRENT_END_LABEL = "Текущий сезон завершится"
SEASON_NEW_START_LABEL = "Новый сезон начнётся"
ADMIN_CALENDAR_TOURNAMENTS_CREATED = "Расписание создано."
TOURNAMENTS_MANUAL_PROPOSAL_TITLE = "Будет создано расписание:"
TOURNAMENTS_CREATED_TITLE = "Создано расписание:"
TOURNAMENT_ENTRY_LABEL = "Вход:"
TOURNAMENT_REBUYS_LABEL = "Ребаи:"
TOURNAMENT_ADDON_LABEL = "Аддон:"
ADMIN_CALENDAR_EDIT_SEASON = "Ок, не открываю сезон. Пришли правки отдельным сообщением."
ADMIN_CALENDAR_EDIT_MENU = "Что меняем?"
ADMIN_CALENDAR_ENTER_SEASON_NEW_NAME = "Введи новое название сезона."
ADMIN_CALENDAR_ENTER_SEASON_NEW_START = (
    "Введи новую дату начала в формате 1.09.2026. "
    "Дата начала нового сезона должна быть позже сегодняшней даты!"
)
ADMIN_CALENDAR_INVALID_DATE = "Дата должна быть в формате 1.09.2026."
ADMIN_CALENDAR_SEASON_NAME_EXISTS = "Сезон с таким названием уже существует."
ADMIN_CALENDAR_SCORING_CONFIG_NOT_FOUND = "Конфигурация начисления рейтинга не найдена."
ADMIN_CALENDAR_SEASON_START_INVALID = (
    "Дата начала нового сезона должна быть позже даты начала текущего активного сезона."
)
ADMIN_CALENDAR_SEASON_CONFLICT = "Не удалось открыть сезон. Попробуй ещё раз."
ADMIN_CALENDAR_SEASON_ALREADY_HANDLED = "Сценарий открытия сезона уже завершён."

CALENDAR_PROMPT_NOT_FOUND = "Предложение не найдено."
CALENDAR_PROMPT_STALE = "Предложение устарело. Открой Турниры заново."
CALENDAR_PROMPT_ALREADY_RESOLVED = "Предложение уже обработано."
CALENDAR_PROMPT_CONFIRMED = "Подтверждено"
CALENDAR_PROMPT_CANCELLED = "Отменено"
CALENDAR_WEEKLY_PROMPT_EMPTY = "В расписании должен остаться хотя бы один турнир."

SEASON_PROPOSAL_TITLE = "Нужно подготовить следующий сезон."
SEASON_PROPOSAL_LABEL = "Предложение"
SEASON_START_LABEL = "Дата начала"
SEASON_SCORING_CONFIG_LABEL = "Конфигурация рейтинга"
TOURNAMENTS_PROPOSAL_TITLE = "Нужно создать расписание."
CONFIRM_CREATION_PROMPT = "Подтвердить создание?"
